export const FETCH_GET_ALL_CLIENTS_ACCOUNTS_REQUEST = "FETCH_GET_ALL_CLIENTS_ACCOUNTS_REQUEST";
export const FETCH_GET_ALL_CLIENTS_ACCOUNTS_SUCCESS = "FETCH_GET_ALL_CLIENTS_ACCOUNTS_SUCCESS";   
export const FETCH_GET_ALL_CLIENTS_ACCOUNTS_FAILURE = "FETCH_GET_ALL_CLIENTS_ACCOUNTS_FAILURE";
export const FETCH_ADD_CLIENT_ACCOUNT_FAILURE = "FETCH_ADD_CLIENT_ACCOUNT_FAILURE";
export const FETCH_ADD_CLIENT_ACCOUNT = "FETCH_ADD_CLIENT_ACCOUNT";
export const FETCH_EDIT_CLIENT_ACCOUNT = "FETCH_EDIT_CLIENT_ACCOUNT";
export const FETCH_INIT_EDIT_CLIENT_ACCOUNT = "FETCH_INIT_EDIT_CLIENT_ACCOUNT";
export const FETCH_DELETE_ALL_CLIENTS_ACCOUNTS_SUCCESS = "FETCH_DELETE_ALL_CLIENTS_ACCOUNTS_SUCCESS"