export const FETCH_GET_ALL_VEHICLES_REQUEST = "FETCH_GET_ALL_VEHICLES_REQUEST";
export const FETCH_GET_ALL_VEHICLES_SUCCESS = "FETCH_GET_ALL_VEHICLES_SUCCESS";   
export const FETCH_GET_ALL_VEHICLES_FAILURE = "FETCH_GET_ALL_VEHICLES_FAILURE";
export const FETCH_ADD_VEHICLE_FAILURE = "FETCH_ADD_VEHICLE_FAILURE";
export const FETCH_ADD_VEHICLE = "FETCH_ADD_VEHICLE";
export const FETCH_EDIT_VEHICLE = "FETCH_EDIT_VEHICLE";
export const FETCH_INIT_EDIT_VEHICLE = "FETCH_INIT_EDIT_VEHICLE";
export const FETCH_DELETE_ALL_VEHICLES_SUCCESS = "FETCH_DELETE_ALL_VEHICLES_SUCCESS"