export const FETCH_GET_ALL_DRIVERS_ACCOUNTS_REQUEST = "FETCH_GET_ALL_DRIVERS_ACCOUNTS_REQUEST";
export const FETCH_GET_ALL_DRIVERS_ACCOUNTS_SUCCESS = "FETCH_GET_ALL_DRIVERS_ACCOUNTS_SUCCESS";   
export const FETCH_GET_ALL_DRIVERS_ACCOUNTS_FAILURE = "FETCH_GET_ALL_DRIVERS_ACCOUNTS_FAILURE";
export const FETCH_ADD_DRIVER_ACCOUNT_FAILURE = "FETCH_ADD_DRIVER_ACCOUNT_FAILURE";
export const FETCH_ADD_DRIVER_ACCOUNT = "FETCH_ADD_DRIVER_ACCOUNT";
export const FETCH_EDIT_DRIVER_ACCOUNT = "FETCH_EDIT_DRIVER_ACCOUNT";
export const FETCH_INIT_EDIT_DRIVER_ACCOUNT = "FETCH_INIT_EDIT_DRIVER_ACCOUNT";
export const FETCH_DELETE_ALL_DRIVERS_ACCOUNTS_SUCCESS = "FETCH_DELETE_ALL_DRIVERS_ACCOUNTS_SUCCESS"