export const FETCH_GET_ALL_CHARGES_REQUEST = "FETCH_GET_ALL_CHARGES_REQUEST";
export const FETCH_GET_ALL_CHARGES_SUCCESS = "FETCH_GET_ALL_CHARGES_SUCCESS";   
export const FETCH_GET_ALL_CHARGES_FAILURE = "FETCH_GET_ALL_CHARGES_FAILURE";
export const FETCH_ADD_CHARGE_FAILURE = "FETCH_ADD_CHARGE_FAILURE";
export const FETCH_ADD_CHARGE = "FETCH_ADD_CHARGE";
export const FETCH_EDIT_CHARGE = "FETCH_EDIT_CHARGE";
export const FETCH_INIT_EDIT_CHARGE = "FETCH_INIT_EDIT_CHARGE";
export const FETCH_DELETE_ALL_CHARGES_SUCCESS = "FETCH_DELETE_ALL_CHARGES_SUCCESS"