export const FETCH_GET_ALL_CUSTOMERS_REQUEST = "FETCH_GET_ALL_CUSTOMERS_REQUEST";
export const FETCH_GET_ALL_CUSTOMERS_SUCCESS = "FETCH_GET_ALL_CUSTOMERS_SUCCESS";   
export const FETCH_GET_ALL_CUSTOMERS_FAILURE = "FETCH_GET_ALL_CUSTOMERS_FAILURE";
export const FETCH_ADD_CUSTOMER_FAILURE = "FETCH_ADD_CUSTOMER_FAILURE";
export const FETCH_ADD_CUSTOMER = "FETCH_ADD_CUSTOMER";
export const FETCH_EDIT_CUSTOMER = "FETCH_EDIT_CUSTOMER";
export const FETCH_INIT_EDIT_CUSTOMER = "FETCH_INIT_EDIT_CUSTOMER";
export const FETCH_DELETE_ALL_CUSTOMERS_SUCCESS = "FETCH_DELETE_ALL_CUSTOMERS_SUCCESS"