export const FETCH_GET_ALL_DRIVERS_REQUEST = "FETCH_GET_ALL_DRIVERS_REQUEST";
export const FETCH_GET_ALL_DRIVERS_SUCCESS = "FETCH_GET_ALL_DRIVERS_SUCCESS";   
export const FETCH_GET_ALL_DRIVERS_FAILURE = "FETCH_GET_ALL_DRIVERS_FAILURE";
export const FETCH_ADD_DRIVER_FAILURE = "FETCH_ADD_DRIVER_FAILURE";
export const FETCH_ADD_DRIVER = "FETCH_ADD_DRIVER";
export const FETCH_EDIT_DRIVER = "FETCH_EDIT_DRIVER";
export const FETCH_INIT_EDIT_DRIVER = "FETCH_INIT_EDIT_DRIVER";
export const FETCH_DELETE_ALL_DRIVERS_SUCCESS = "FETCH_DELETE_ALL_DRIVERS_SUCCESS"