export const FETCH_GET_ALL_CLIENTS_REQUEST = "FETCH_GET_ALL_CLIENTS_REQUEST";
export const FETCH_GET_ALL_CLIENTS_SUCCESS = "FETCH_GET_ALL_CLIENTS_SUCCESS";   
export const FETCH_GET_ALL_CLIENTS_FAILURE = "FETCH_GET_ALL_CLIENTS_FAILURE";
export const FETCH_ADD_CLIENT_FAILURE = "FETCH_ADD_CLIENT_FAILURE";
export const FETCH_ADD_CLIENT = "FETCH_ADD_CLIENT";
export const FETCH_EDIT_CLIENT = "FETCH_EDIT_CLIENT";
export const FETCH_INIT_EDIT_CLIENT = "FETCH_INIT_EDIT_CLIENT";
export const FETCH_DELETE_ALL_CLIENTS_SUCCESS = "FETCH_DELETE_ALL_CLIENTS_SUCCESS"