export const FETCH_GET_ALL_ORDERS_REQUEST = "FETCH_GET_ALL_ORDERS_REQUEST";
export const FETCH_GET_ALL_ORDERS_SUCCESS = "FETCH_GET_ALL_ORDERS_SUCCESS";   
export const FETCH_GET_ALL_ORDERS_FAILURE = "FETCH_GET_ALL_ORDERS_FAILURE";
export const FETCH_ADD_ORDER_FAILURE = "FETCH_ADD_ORDER_FAILURE";
export const FETCH_ADD_ORDER = "FETCH_ADD_ORDER";
export const FETCH_EDIT_ORDER = "FETCH_EDIT_ORDER";
export const FETCH_INIT_EDIT_ORDER = "FETCH_INIT_EDIT_ORDER";
export const FETCH_DELETE_ALL_ORDERS_SUCCESS = "FETCH_DELETE_ALL_ORDERS_SUCCESS"